// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFlp2gM2cXIeaoEzaPvppyIzV5RpZASD0',
    appId: '1:1025516160796:web:69c15de676b3b44c4d9cd9',
    messagingSenderId: '1025516160796',
    projectId: 'newsly-70ef9',
    authDomain: 'newsly-70ef9.firebaseapp.com',
    storageBucket: 'newsly-70ef9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOmFjOKTt-r7Py5KLH_LDIKRe9AqjuVX4',
    appId: '1:1025516160796:android:b25dce3202262db44d9cd9',
    messagingSenderId: '1025516160796',
    projectId: 'newsly-70ef9',
    storageBucket: 'newsly-70ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqYxzWHPPHcFl8JLNlAxvEq53TBsGSKuQ',
    appId: '1:1025516160796:ios:e027e9650e2baf2a4d9cd9',
    messagingSenderId: '1025516160796',
    projectId: 'newsly-70ef9',
    storageBucket: 'newsly-70ef9.firebasestorage.app',
    iosBundleId: 'com.newsly.haber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqYxzWHPPHcFl8JLNlAxvEq53TBsGSKuQ',
    appId: '1:1025516160796:ios:8dbf9b988db56e6e4d9cd9',
    messagingSenderId: '1025516160796',
    projectId: 'newsly-70ef9',
    storageBucket: 'newsly-70ef9.firebasestorage.app',
    iosBundleId: 'com.example.haber',
  );
}
